[versions]
# libraries
annotations = "26.0.2"
junit = "4.13.2"

# plugins
kotlin = "2.2.10"
changelog = "2.4.0"
qodana = "0.1.13"

kover = "0.9.3"
intelliJPlatform = "2.7.2"
kotlinxHtml = "0.12.0"

ktor = "3.3.1"
kotlinSdk = "0.7.4"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
kotlinxHtml = { group = "org.jetbrains.kotlinx", name = "kotlinx-html", version.ref = "kotlinxHtml" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ktorServer = {group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor"}
kotlinSdk = {group = "io.modelcontextprotocol", name = "kotlin-sdk", version.ref = "kotlinSdk"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
